### ISSUE TITLE
warn: Ignoring non-link key added to list

### ISSUE THREAD

**Issue by aultac** [OADA/list-lib#3]
This statement prints a lot a the moment.

**Comment by awlayton** [comment]
I mean we could get rid of that print statement. or make it an info or something. It's not exactly a bad thing I supposed

**Comment by aultac** [comment]
In unfisk, 98% of the logs are that print statement.  Perhaps an underlying library like this should be confining all its print statements to `trace` and let the higher-level thing do info/warn/error printing?

**Comment by awlayton** [comment]
Unfisk does not use this lib

**Comment by aultac** [comment]
Sorry, I meant target-helper's logs.  It's getting late in the day for farmers like me....  :)

**Comment by awlayton** [comment]
I say we just move it to trace or something. You're seeing it a lot because
you have an index so it sees changes in the middle of the index and ignores
them.

**Comment by aultac** [comment]
Agreed, move to trace.  As a general takeaway, should our internal libs limit themselves to trace?  I mean, their messages ARE prefixed and theoretically can be turned off, but we have a handy-dandy default `DEBUG=*info*,*warn*,*error*` that we can just export to environment on any deployments by default.  I mean, in theory it should be `DEBUG=<service>:info,<service>:warn,<service>:error`, but it seems like too much detail to get that right everywhere w/o thinking about it too much.  Maybe some kind of `-*lib*` in the default which would turn off any debugs w/ "lib" in the name?

**Comment by awlayton** [comment]
I don't think the libs should limit themselves to trace. if you don't want them on, don't turn on their debug.
