### ISSUE TITLE
Fix oada/client to give us changeset so we can properly save parent rev to _meta/oada-list-lib

### ISSUE THREAD

**Issue by aultac** [OADA/list-lib#4]
Currently, it saves parent rev to _meta/oada-list-lib whenever that change is received.  It should not save it unless all the changes under that parent rev have been successfully handled.  Need to update oada/client to give us the changeset all at once instead of looping over it internally and giving us only the individual changes.

**Comment by awlayton** [comment]
fixed in 2.1.1
